name: habit_tracker
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  cloud_firestore: ^5.6.3
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  firebase_dynamic_links: ^6.1.1
  firebase_ui_auth: ^1.16.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  lottie: ^3.2.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
